name: Dogs Service CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Chek EsLint
      uses: yarn lint

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn test
      env:
        CI: true